// Code generated by gobind. DO NOT EDIT.

// Java class io.nekohasekai.libbox.HTTPRequest is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=io.nekohasekai github.com/sagernet/sing-box/experimental/libbox
package io.nekohasekai.libbox;

import go.Seq;

public interface HTTPRequest {
	public HTTPResponse execute() throws Exception;
	public void randomUserAgent();
	public void setContent(byte[] content);
	public void setContentString(String content);
	public void setHeader(String key, String value);
	public void setMethod(String method);
	public void setURL(String link) throws Exception;
	public void setUserAgent(String userAgent);
	
}

