// Code generated by gobind. DO NOT EDIT.

// Java class io.nekohasekai.libbox.ImportRemoteProfile is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=io.nekohasekai github.com/sagernet/sing-box/experimental/libbox
package io.nekohasekai.libbox;

import go.Seq;

public final class ImportRemoteProfile implements Seq.Proxy {
	static { Libbox.touch(); }
	
	public final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	ImportRemoteProfile(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public ImportRemoteProfile() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native String getName();
	public final native void setName(String v);
	
	public final native String getURL();
	public final native void setURL(String v);
	
	public final native String getHost();
	public final native void setHost(String v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof ImportRemoteProfile)) {
		    return false;
		}
		ImportRemoteProfile that = (ImportRemoteProfile)o;
		String thisName = getName();
		String thatName = that.getName();
		if (thisName == null) {
			if (thatName != null) {
			    return false;
			}
		} else if (!thisName.equals(thatName)) {
		    return false;
		}
		String thisURL = getURL();
		String thatURL = that.getURL();
		if (thisURL == null) {
			if (thatURL != null) {
			    return false;
			}
		} else if (!thisURL.equals(thatURL)) {
		    return false;
		}
		String thisHost = getHost();
		String thatHost = that.getHost();
		if (thisHost == null) {
			if (thatHost != null) {
			    return false;
			}
		} else if (!thisHost.equals(thatHost)) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getName(), getURL(), getHost()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("ImportRemoteProfile").append("{");
		b.append("Name:").append(getName()).append(",");
		b.append("URL:").append(getURL()).append(",");
		b.append("Host:").append(getHost()).append(",");
		return b.append("}").toString();
	}
}

