// Code generated by gobind. DO NOT EDIT.

// Java class io.nekohasekai.libbox.LocalDNSTransport is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=io.nekohasekai github.com/sagernet/sing-box/experimental/libbox
package io.nekohasekai.libbox;

import go.Seq;

public interface LocalDNSTransport {
	public void exchange(ExchangeContext ctx, byte[] message) throws Exception;
	public void lookup(ExchangeContext ctx, String network, String domain) throws Exception;
	public boolean raw();
	
}

