// Code generated by gobind. DO NOT EDIT.

// Java class io.nekohasekai.libbox.OnDemandRule is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=io.nekohasekai github.com/sagernet/sing-box/experimental/libbox
package io.nekohasekai.libbox;

import go.Seq;

public interface OnDemandRule {
	public StringIterator dnsSearchDomainMatch();
	public StringIterator dnsServerAddressMatch();
	public int interfaceTypeMatch();
	public String probeURL();
	public StringIterator ssidMatch();
	public int target();
	
}

