// Code generated by gobind. DO NOT EDIT.

// Java class io.nekohasekai.libbox.OutboundGroupItem is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=io.nekohasekai github.com/sagernet/sing-box/experimental/libbox
package io.nekohasekai.libbox;

import go.Seq;

public final class OutboundGroupItem implements Seq.Proxy {
	static { Libbox.touch(); }
	
	public final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	OutboundGroupItem(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public OutboundGroupItem() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native String getTag();
	public final native void setTag(String v);
	
	public final native String getType();
	public final native void setType(String v);
	
	public final native long getURLTestTime();
	public final native void setURLTestTime(long v);
	
	public final native int getURLTestDelay();
	public final native void setURLTestDelay(int v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof OutboundGroupItem)) {
		    return false;
		}
		OutboundGroupItem that = (OutboundGroupItem)o;
		String thisTag = getTag();
		String thatTag = that.getTag();
		if (thisTag == null) {
			if (thatTag != null) {
			    return false;
			}
		} else if (!thisTag.equals(thatTag)) {
		    return false;
		}
		String thisType = getType();
		String thatType = that.getType();
		if (thisType == null) {
			if (thatType != null) {
			    return false;
			}
		} else if (!thisType.equals(thatType)) {
		    return false;
		}
		long thisURLTestTime = getURLTestTime();
		long thatURLTestTime = that.getURLTestTime();
		if (thisURLTestTime != thatURLTestTime) {
		    return false;
		}
		int thisURLTestDelay = getURLTestDelay();
		int thatURLTestDelay = that.getURLTestDelay();
		if (thisURLTestDelay != thatURLTestDelay) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getTag(), getType(), getURLTestTime(), getURLTestDelay()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("OutboundGroupItem").append("{");
		b.append("Tag:").append(getTag()).append(",");
		b.append("Type:").append(getType()).append(",");
		b.append("URLTestTime:").append(getURLTestTime()).append(",");
		b.append("URLTestDelay:").append(getURLTestDelay()).append(",");
		return b.append("}").toString();
	}
}

