// Code generated by gobind. DO NOT EDIT.

// Java class io.nekohasekai.libbox.PProfServer is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=io.nekohasekai github.com/sagernet/sing-box/experimental/libbox
package io.nekohasekai.libbox;

import go.Seq;

public final class PProfServer implements Seq.Proxy {
	static { Libbox.touch(); }
	
	public final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	public PProfServer(long port) {
		this.refnum = __NewPProfServer(port);
		Seq.trackGoRef(refnum, this);
	}
	
	private static native int __NewPProfServer(long port);
	
	PProfServer(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public native void close() throws Exception;
	public native void start() throws Exception;
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof PProfServer)) {
		    return false;
		}
		PProfServer that = (PProfServer)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("PProfServer").append("{");
		return b.append("}").toString();
	}
}

