// Code generated by gobind. DO NOT EDIT.

// Java class io.nekohasekai.libbox.ProfileEncoder is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=io.nekohasekai github.com/sagernet/sing-box/experimental/libbox
package io.nekohasekai.libbox;

import go.Seq;

public final class ProfileEncoder implements Seq.Proxy {
	static { Libbox.touch(); }
	
	public final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	ProfileEncoder(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public ProfileEncoder() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public native void append(ProfilePreview profile);
	public native byte[] encode();
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof ProfileEncoder)) {
		    return false;
		}
		ProfileEncoder that = (ProfileEncoder)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("ProfileEncoder").append("{");
		return b.append("}").toString();
	}
}

