// Code generated by gobind. DO NOT EDIT.

// Java class io.nekohasekai.libbox.ProfileContentRequest is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=io.nekohasekai github.com/sagernet/sing-box/experimental/libbox
package io.nekohasekai.libbox;

import go.Seq;

public final class ProfileContentRequest implements Seq.Proxy {
	static { Libbox.touch(); }
	
	public final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	ProfileContentRequest(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public ProfileContentRequest() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native long getProfileID();
	public final native void setProfileID(long v);
	
	public native byte[] encode();
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof ProfileContentRequest)) {
		    return false;
		}
		ProfileContentRequest that = (ProfileContentRequest)o;
		long thisProfileID = getProfileID();
		long thatProfileID = that.getProfileID();
		if (thisProfileID != thatProfileID) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getProfileID()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("ProfileContentRequest").append("{");
		b.append("ProfileID:").append(getProfileID()).append(",");
		return b.append("}").toString();
	}
}

