// Code generated by gobind. DO NOT EDIT.

// Java class io.nekohasekai.libbox.TunOptions is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=io.nekohasekai github.com/sagernet/sing-box/experimental/libbox
package io.nekohasekai.libbox;

import go.Seq;

public interface TunOptions {
	public boolean getAutoRoute();
	public String getDNSServerAddress() throws Exception;
	public StringIterator getExcludePackage();
	public StringIterator getHTTPProxyBypassDomain();
	public StringIterator getHTTPProxyMatchDomain();
	public String getHTTPProxyServer();
	public int getHTTPProxyServerPort();
	public StringIterator getIncludePackage();
	public RoutePrefixIterator getInet4Address();
	public RoutePrefixIterator getInet4RouteAddress();
	public RoutePrefixIterator getInet4RouteExcludeAddress();
	public RoutePrefixIterator getInet4RouteRange();
	public RoutePrefixIterator getInet6Address();
	public RoutePrefixIterator getInet6RouteAddress();
	public RoutePrefixIterator getInet6RouteExcludeAddress();
	public RoutePrefixIterator getInet6RouteRange();
	public int getMTU();
	public boolean getStrictRoute();
	public boolean isHTTPProxyEnabled();
	
}

