// Code generated by gobind. DO NOT EDIT.

// Java class io.nekohasekai.libbox.CommandClientHandler is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=io.nekohasekai github.com/sagernet/sing-box/experimental/libbox
package io.nekohasekai.libbox;

import go.Seq;

public interface CommandClientHandler {
	public void clearLog();
	public void connected();
	public void disconnected(String message);
	public void initializeClashMode(StringIterator modeList, String currentMode);
	public void updateClashMode(String newMode);
	public void writeGroups(OutboundGroupIterator message);
	public void writeLog(String message);
	public void writeStatus(StatusMessage message);
	
}

