// Code generated by gobind. DO NOT EDIT.

// Java class io.nekohasekai.libbox.CommandClientOptions is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=io.nekohasekai github.com/sagernet/sing-box/experimental/libbox
package io.nekohasekai.libbox;

import go.Seq;

public final class CommandClientOptions implements Seq.Proxy {
	static { Libbox.touch(); }
	
	public final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	CommandClientOptions(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public CommandClientOptions() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native int getCommand();
	public final native void setCommand(int v);
	
	public final native long getStatusInterval();
	public final native void setStatusInterval(long v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof CommandClientOptions)) {
		    return false;
		}
		CommandClientOptions that = (CommandClientOptions)o;
		int thisCommand = getCommand();
		int thatCommand = that.getCommand();
		if (thisCommand != thatCommand) {
		    return false;
		}
		long thisStatusInterval = getStatusInterval();
		long thatStatusInterval = that.getStatusInterval();
		if (thisStatusInterval != thatStatusInterval) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getCommand(), getStatusInterval()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("CommandClientOptions").append("{");
		b.append("Command:").append(getCommand()).append(",");
		b.append("StatusInterval:").append(getStatusInterval()).append(",");
		return b.append("}").toString();
	}
}

