// Code generated by gobind. DO NOT EDIT.

// Java class io.nekohasekai.libbox.HTTPResponse is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=io.nekohasekai github.com/sagernet/sing-box/experimental/libbox
package io.nekohasekai.libbox;

import go.Seq;

public interface HTTPResponse {
	public byte[] getContent() throws Exception;
	public String getContentString() throws Exception;
	public void writeTo(String path) throws Exception;
	
}

