// Code generated by gobind. DO NOT EDIT.

// Java class io.nekohasekai.libbox.PlatformInterface is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=io.nekohasekai github.com/sagernet/sing-box/experimental/libbox
package io.nekohasekai.libbox;

import go.Seq;

public interface PlatformInterface {
	public void autoDetectInterfaceControl(int fd) throws Exception;
	public void clearDNSCache();
	public void closeDefaultInterfaceMonitor(InterfaceUpdateListener listener) throws Exception;
	public int findConnectionOwner(int ipProtocol, String sourceAddress, int sourcePort, String destinationAddress, int destinationPort) throws Exception;
	public NetworkInterfaceIterator getInterfaces() throws Exception;
	public int openTun(TunOptions options) throws Exception;
	public String packageNameByUid(int uid) throws Exception;
	public WIFIState readWIFIState();
	public void startDefaultInterfaceMonitor(InterfaceUpdateListener listener) throws Exception;
	public int uidByPackageName(String packageName) throws Exception;
	public boolean underNetworkExtension();
	public boolean usePlatformAutoDetectInterfaceControl();
	public boolean usePlatformDefaultInterfaceMonitor();
	public boolean usePlatformInterfaceGetter();
	public boolean useProcFS();
	public void writeLog(String message);
	
}

