// Code generated by gobind. DO NOT EDIT.

// Java class io.nekohasekai.libbox.ProfileDecoder is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=io.nekohasekai github.com/sagernet/sing-box/experimental/libbox
package io.nekohasekai.libbox;

import go.Seq;

public final class ProfileDecoder implements Seq.Proxy {
	static { Libbox.touch(); }
	
	public final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	ProfileDecoder(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public ProfileDecoder() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public native void decode(byte[] data) throws Exception;
	public native ProfilePreviewIterator iterator();
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof ProfileDecoder)) {
		    return false;
		}
		ProfileDecoder that = (ProfileDecoder)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("ProfileDecoder").append("{");
		return b.append("}").toString();
	}
}

