// Code generated by gobind. DO NOT EDIT.

// Java class io.nekohasekai.libbox.RoutePrefix is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=io.nekohasekai github.com/sagernet/sing-box/experimental/libbox
package io.nekohasekai.libbox;

import go.Seq;

public final class RoutePrefix implements Seq.Proxy {
	static { Libbox.touch(); }
	
	public final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	RoutePrefix(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public RoutePrefix() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public native String address();
	public native String mask();
	public native int prefix();
	public native String string();
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof RoutePrefix)) {
		    return false;
		}
		RoutePrefix that = (RoutePrefix)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		return string();
	}
}

