// Code generated by gobind. DO NOT EDIT.

// Java class io.nekohasekai.libbox.StringIterator is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=io.nekohasekai github.com/sagernet/sing-box/experimental/libbox
package io.nekohasekai.libbox;

import go.Seq;

public interface StringIterator {
	public boolean hasNext();
	public String next();
	
}

